### ISSUE TITLE
template can not import zabbix 2.2.7

### ISSUE THREAD

**Issue by redbox-cdn** [lorf/zapache#3]
Hi 
The xml templates can not import to  zabbix 2.2.7.

Error message is occurred.

**Comment by Thomas-Ganter** [comment]
Worken fine on my Zabbix 2.2.5

**Comment by livti** [comment]
Hi,

I'm having difficulties as well, Zabbix 2.4.3, dunno if it is the same message redbox2000 is getting, but the template fails to import for me due to a missing trigger:

Trigger "HTTPd process" depends on trigger "ICMP FRONT", which does not exist.

I've checked the template and ICMP FRONT is listed, but I cannot figure out how to solve it (meaning how should I include or create the missing trigger, given that I am unaware of the parameters).

**Comment by Parasin** [comment]
Works on 2.4
