### ISSUE TITLE
BytesPerReqRealtime

### ISSUE THREAD

**Issue by dmgeurts** [lorf/zapache#8]
The templates refer to "BytesPerReqRealtime" but zapache(.sh) only knows about "BytesPerReq". Why was this item added to the template when the script doesn't know where to get this detail?

**Comment by lorf** [comment]
`BytesPerReqRealtime` is a calculated value taken by dividing last `TotalKBytes` delta by last `TotalAccesses` delta. Zapache script is not involved since calculation is done by Zabbix server. In contrast `BytesPerReq` is a value averaged over time by apache (maybe mean or median, need to look up apache source for exact method) and is taken from apache stats directly.

The `BytesPerReqRealtime` was added to get more detailed picture of what is going on and is used on the graphs, predefinied in template.

Calculated item may be reported as "Not supported" in Zabbix while the values it depends on are not available. Such item will be recalculated after "Unsupported item refresh interval".

**Comment by dmgeurts** [comment]
Thank you for the explanation. I have enabled the item and data is being graphed.
